### ISSUE TITLE
missing required arguments: user

### ISSUE THREAD

**Issue by makorne** [filviu/ansible-role-hetzner_installimage#1]
Hi!
Thank you for interesting role!

But how to setup user in defaults/main.yml?

I set: 
```
hetzner_installimage_sshkeys: 
  - "id_rsa"
```
  
Start:
` ansible-playbook -i "x.x.x.x," -u root -e "hetzner_installimage_cryptpassword=PASSWORD" --private-key=~/.ssh/id_rsa hetzner-installimage.yml `

But get an error:
```
TASK [filviu.hetzner_installimage : setup | setup.conf] **************************************************************************************************************************************
ok: [x.x.x.x]

TASK [filviu.hetzner_installimage : setup | authorized_keys with existing keys] **************************************************************************************************************
skipping: [x.x.x.x]

TASK [filviu.hetzner_installimage : setup | authorized_keys with provided keys] **************************************************************************************************************
failed: [x.x.x.x] (item=id_rsa) => {"ansible_loop_var": "item", "changed": false, "item": "id_rsa", "msg": "missing required arguments: user"}
```

  
I tried set such hetzner-installimage.yml this but this changed nothing

```
---
- hosts: all
  tasks:
    - authorized_key:
        user: remote_user_name
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  roles:
    - role: filviu.hetzner_installimage
      hetzner_installimage_image: "/root/images/Debian-1010-buster-64-minimal.tar.gz"
```

ansible --version
```
ansible [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

How to set user??
Thank you!
